# Learning-to-rank : pyTerrier - OpenNIR

Dans cette partie, on s'intéresse à l'utilisation de modèles neuronaux pour la recherche d'information.
Les modèles neuronaux utilisés ont été rassemblés dans la librairie [OpenNIR](https://opennir.net/).
On explorera également le modèle T5 avec le plugin [monoT5](https://github.com/terrierteam/pyterrier_t5).

In [1]:
!pip install --upgrade python-terrier
!pip install --upgrade git+https://github.com/Georgetown-IR-Lab/OpenNIR
!pip install --upgrade git+https://github.com/terrierteam/pyterrier_t5

Collecting python-terrier
  Downloading python_terrier-1.0-py3-none-any.whl.metadata (987 bytes)
Collecting pyterrier>=1.0 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyterrier-1.0.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.0.2)
Requirement already satisfied: pandas<3.0 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.2.2)
Requirement already satisfied: more_itertools in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (10.8.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.32.4)
Collecting ir_datasets>=0.3.2 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Collecting deprecated (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.16.3)
Collecting ir_measures>=0.4.1 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_measures-0.4.3-py3-none-any.whl.metadata (7.0 kB)
Collecting pytrec_eval_terrier>=0.5.3 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading pytrec_eval_terrier-0.5.10-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.1.6)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.14.6)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.3.8)
Collecting lz4 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.13.5)
Collecting pyjnius>=1.4.2 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyjnius-1.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting inscriptis>=2.2.0 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading inscriptis-2.7.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.0.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.0.3)
Collecting trec-car-tools>=2.5.4 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting warc3-wet>=0.2.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting zlib-state>=0.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pyarrow>=16.1.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (18.1.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.2.25)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.0.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.17.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Downloading python_terrier-1.0-py3-none-any.whl (1.4 kB)
Downloading pyterrier-1.0.4-py3-none-any.whl (208 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.8/208.8 kB 10.1 MB/s eta 0:00:00
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 39.1 MB/s eta 0:00:00
Downloading ir_measures-0.4.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 7.6 MB/s eta 0:00:00
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 81.9 MB/s eta 0:00:00
Downloading pyjnius-1.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 103.1 MB/s eta 0:00:00
Downloading pytrec_eval_terrier-0.5.10-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (304 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.8/304.8 kB 38.0 MB/s eta 0:00:00
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 15.7 MB/s eta 0:00:00
Downloading inscriptis-2.7.1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 5.6 MB/s eta 0:00:00
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Building wheels for collected packages: warc3-wet-clueweb09, cbor
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18919 sha256=4a320b7f1fe9178e73b7fb7e95f8c2d81a2c7cbb56a398a261cebdcb7c9cf0cb
  Stored in directory: /root/.cache/pip/wheels/f6/85/c2/9f0f621def52a1d5db7d29984f81e45f9fb6dfeb1a4eb6e31c
  Building wheel for cbor (setup.py) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp312-cp312-linux_x86_64.whl size=55023 sha256=33a36b1529f31226e0e19de403e8200f00b2d13360d300444e682cfba1117dbb
  Stored in directory: /root/.cache/pip/wheels/44/3e/21/a739cbcc331a1ab45c326d6edbdac6118de4402f6076e30ff1
Successfully built warc3-wet-clueweb09 cbor
Installing collected packages: warc3-wet-clueweb09, warc3-wet, pyjnius, cbor, zlib-state, unlzw3, trec-car-tools, lz4, ijson, deprecated, pytrec_eval_terrier, inscriptis, ir_measures, ir_datasets, pyterrier, python-terrier
Successfully installed cbor-1.0.0 deprecated-1.3.1 ijson-3.5.0 inscriptis-2.7.1 ir_datasets-0.5.11 ir_measures-0.4.3 lz4-4.4.5 pyjnius-1.7.0 pyterrier-1.0.4 python-terrier-1.0 pytrec_eval_terrier-0.5.10 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.10
Collecting git+https://github.com/Georgetown-IR-Lab/OpenNIR
  Cloning https://github.com/Georgetown-IR-Lab/OpenNIR to /tmp/pip-req-build-shd9tbj2
  Running command git clone --filter=blob:none --quiet https://github.com/Georgetown-IR-Lab/OpenNIR /tmp/pip-req-build-shd9tbj2
  Resolved https://github.com/Georgetown-IR-Lab/OpenNIR to commit 69298b42d609e755e430f2d2930062be6a8d56c9
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (2.10.0+cu128)
Collecting pytorch-pretrained-bert==0.6.1 (from OpenNIR==0.1.0)
  Downloading pytorch_pretrained_bert-0.6.1-py3-none-any.whl.metadata (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.7/74.7 kB 4.5 MB/s eta 0:00:00
Collecting pytorch-transformers==1.1.0 (from OpenNIR==0.1.0)
  Downloading pytorch_transformers-1.1.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: tokenizers>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (0.22.2)
Requirement already satisfied: transformers>=4.3.3 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (5.0.0)
Requirement already satisfied: tqdm>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (4.67.3)
Collecting colorlog==4.0.2 (from OpenNIR==0.1.0)
  Downloading colorlog-4.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting terminaltables>=3.1.0 (from OpenNIR==0.1.0)
  Downloading terminaltables-3.1.10-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: matplotlib>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (3.10.0)
Requirement already satisfied: seaborn>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (0.13.2)
Collecting python-ternary>=1.0.6 (from OpenNIR==0.1.0)
  Downloading python_ternary-1.0.8-py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: beautifulsoup4>=4.9.3 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (4.13.5)
Requirement already satisfied: html5lib>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (1.1)
Collecting Unidecode>=1.0.22 (from OpenNIR==0.1.0)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: nltk>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (3.9.1)
Collecting sqlitedict>=1.6.0 (from OpenNIR==0.1.0)
  Downloading sqlitedict-2.1.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pytrec-eval-terrier>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (0.5.10)
Requirement already satisfied: Cython>=0.29.2 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (3.0.12)
Requirement already satisfied: pyjnius>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (1.7.0)
Requirement already satisfied: ir_datasets>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (0.5.11)
Requirement already satisfied: ir_measures>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from OpenNIR==0.1.0) (0.4.3)
Collecting pytools>=2018.5.2 (from OpenNIR==0.1.0)
  Downloading pytools-2026.1-py3-none-any.whl.metadata (2.9 kB)
Collecting cached-property>=1.5.1 (from OpenNIR==0.1.0)
  Downloading cached_property-2.0.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pytorch-pretrained-bert==0.6.1->OpenNIR==0.1.0) (2.0.2)
Collecting boto3 (from pytorch-pretrained-bert==0.6.1->OpenNIR==0.1.0)
  Downloading boto3-1.42.88-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pytorch-pretrained-bert==0.6.1->OpenNIR==0.1.0) (2.32.4)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from pytorch-pretrained-bert==0.6.1->OpenNIR==0.1.0) (2025.11.3)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from pytorch-transformers==1.1.0->OpenNIR==0.1.0) (0.2.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.9.3->OpenNIR==0.1.0) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.9.3->OpenNIR==0.1.0) (4.15.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.12/dist-packages (from html5lib>=1.0.1->OpenNIR==0.1.0) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from html5lib>=1.0.1->OpenNIR==0.1.0) (0.5.1)
Requirement already satisfied: inscriptis>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (2.7.1)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (6.0.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (6.0.3)
Requirement already satisfied: trec-car-tools>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (2.6)
Requirement already satisfied: lz4>=3.1.10 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (4.4.5)
Requirement already satisfied: warc3-wet>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (0.2.5)
Requirement already satisfied: warc3-wet-clueweb09>=0.2.5 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (0.2.5)
Requirement already satisfied: zlib-state>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (0.1.10)
Requirement already satisfied: ijson>=3.1.3 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (3.5.0)
Requirement already satisfied: unlzw3>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (0.2.3)
Requirement already satisfied: pyarrow>=16.1.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.2.0->OpenNIR==0.1.0) (18.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.2->OpenNIR==0.1.0) (2.9.0.post0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.4.5->OpenNIR==0.1.0) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.4.5->OpenNIR==0.1.0) (1.5.3)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pytools>=2018.5.2->OpenNIR==0.1.0) (4.9.4)
Collecting siphash24>=1.6 (from pytools>=2018.5.2->OpenNIR==0.1.0)
  Downloading siphash24-1.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from pytrec-eval-terrier>=0.5.1->OpenNIR==0.1.0) (1.16.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn>=0.9.0->OpenNIR==0.1.0) (2.2.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.1.1->OpenNIR==0.1.0) (1.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (3.25.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3.1->OpenNIR==0.1.0) (12.8.90)

## Initialisation
De façon similaire au TP1, on initialise PyTerrier. Nous allons travailler sur le dataset CORD19. le bloc suivant est une répétition du code en TP1.

In [2]:
import pyterrier as pt
if not pt.started():
    pt.init(tqdm='notebook')
import onir_pt

terrier-assemblies 5.11 jar-with-dependencies not found, downloading to /root/.pyterrier...

/tmp/ipykernel_380/3869899361.py:2: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():

https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/5.11/terrier-assemblies-5.11-jar-with-dependenci…

Done
terrier-python-helper 0.0.8 jar not found, downloading to /root/.pyterrier...

https://repo1.maven.org/maven2/org/terrier/terrier-python-helper/0.0.8/terrier-python-helper-0.0.8.jar:   0%| …

Done

Java started and loaded: pyterrier.java.colab, pyterrier.java, pyterrier.java.24, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
/tmp/ipykernel_380/3869899361.py:3: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
The following code will have the same effect:
pt.utils.set_tqdm('notebook')
pt.java.init() # optional, forces java initialisation
  pt.init(tqdm='notebook')

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.

In [3]:
import os

dataset = pt.datasets.get_dataset('irds:cord19/trec-covid')
topics = dataset.get_topics(variant='description')
qrels = dataset.get_qrels()

indexer = pt.index.IterDictIndexer('./cord19-index', text_attrs=['title', 'abstract'], fields=True)
indexref = indexer.index(dataset.get_corpus_iter())
index = pt.IndexFactory.of(indexref)

[INFO] [starting] https://ir.nist.gov/covidSubmit/data/topics-rnd5.xml
[INFO] [finished] https://ir.nist.gov/covidSubmit/data/topics-rnd5.xml: [1ms] [18.7kB] [21.6MB/s]
[INFO] [starting] https://ir.nist.gov/covidSubmit/data/qrels-covid_d5_j0.5-5.txt
[INFO] [finished] https://ir.nist.gov/covidSubmit/data/qrels-covid_d5_j0.5-5.txt: [317ms] [1.14MB] [3.60MB/s]
[INFO] [starting] building docstore
[INFO] If you have a local copy of https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/80d664e496b8b7e50a39c6f6bb92e0ef
[INFO] [starting] https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv
docs_iter:   0%|                                    | 0/192509 [251ms<?, ?doc/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.0%| 0.00/269M [0ms<?, ?B/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 1.0%| 2.63M/269M [104ms<10.59s, 25.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 3.0%| 8.09M/269M [206ms<6.64s, 39.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 5.9%| 15.9M/269M [306ms<4.86s, 52.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 8.8%| 23.8M/269M [505ms<5.22s, 47.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 11.7%| 31.6M/269M [660ms<4.96s, 47.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 14.7%| 39.4M/269M [875ms<5.10s, 45.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 17.6%| 47.3M/269M [1.02s<4.77s, 46.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 20.5%| 55.1M/269M [1.27s<4.93s, 43.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 23.4%| 63.0M/269M [1.45s<4.74s, 43.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 26.3%| 70.8M/269M [1.61s<4.52s, 43.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 29.2%| 78.6M/269M [1.80s<4.36s, 43.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 32.1%| 86.5M/269M [1.99s<4.21s, 43.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 35.0%| 94.3M/269M [2.12s<3.93s, 44.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 37.9%| 102M/269M [2.25s<3.67s, 45.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 40.9%| 110M/269M [2.37s<3.44s, 46.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 43.8%| 118M/269M [2.50s<3.21s, 47.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 46.7%| 126M/269M [2.61s<2.98s, 48.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 49.6%| 134M/269M [2.75s<2.79s, 48.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 52.5%| 141M/269M [2.87s<2.60s, 49.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 55.4%| 149M/269M [3.09s<2.49s, 48.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 58.3%| 157M/269M [3.29s<2.35s, 47.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 61.2%| 165M/269M [3.46s<2.19s, 47.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 64.2%| 173M/269M [3.60s<2.01s, 48.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 67.1%| 181M/269M [3.71s<1.82s, 48.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 70.0%| 188M/269M [3.93s<1.69s, 47.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 72.9%| 196M/269M [4.10s<1.53s, 47.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 75.8%| 204M/269M [4.21s<1.34s, 48.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 78.7%| 212M/269M [4.51s<1.22s, 46.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 81.6%| 220M/269M [4.66s<1.05s, 47.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 84.5%| 228M/269M [4.77s<873ms, 47.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 87.5%| 235M/269M [4.88s<701ms, 48.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 90.4%| 243M/269M [5.15s<550ms, 47.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 93.3%| 251M/269M [5.25s<378ms, 47.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 96.2%| 259M/269M [5.40s<213ms, 48.0MB/s]

[INFO] [finished] https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: [5.58s] [269MB] [48.3MB/s]
docs_iter:   0%|                                    | 0/192509 [5.84s<?, ?doc/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: [5.58s] [269MB] [48.2MB/s]
docs_iter: 100%|█████████████████████| 192509/192509 [14.84s<0ms, 12971.73doc/s]
[INFO] [finished] docs_iter: [14.84s] [192509doc] [12971.15doc/s]
[INFO] [finished] building docstore [14.85s]

cord19/trec-covid documents:   0%|          | 0/192509 [6ms<?, ?it/s]

10:21:14.127 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (8is9x9sc) - further warnings are suppressed
10:22:22.622 [ForkJoinPool-1-worker-1] ERROR org.terrier.structures.indexing.Indexer -- Could not finish MetaIndexBuilder:
java.io.IOException: Key 8lqzfj2e is not unique: 37597,11755
For MetaIndex, to suppress, set metaindex.compressed.reverse.allow.duplicates=true
	at org.terrier.structures.collections.FSOrderedMapFile$MultiFSOMapWriter.mergeTwo(FSOrderedMapFile.java:1374)
	at org.terrier.structures.collections.FSOrderedMapFile$MultiFSOMapWriter.close(FSOrderedMapFile.java:1308)
	at org.terrier.structures.indexing.BaseMetaIndexBuilder.close(BaseMetaIndexBuilder.java:321)
	at org.terrier.structures.indexing.classical.BasicIndexer.indexDocuments(BasicIndexer.java:270)
	at org.terrier.structures.indexing.classical.BasicIndexer.createDirectIndex(BasicIndexer.java:388)
	at org.terrier.structures.indexing.Indexer.index(Indexer.java:377)
	at org.terrier.python.ParallelIndexer$3.apply(ParallelIndexer.java:131)
	at org.terrier.python.ParallelIndexer$3.apply(ParallelIndexer.java:120)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at org.terrier.python.ParallelIndexer$4.call(ParallelIndexer.java:140)
	at org.terrier.python.ParallelIndexer$4.call(ParallelIndexer.java:137)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
10:22:30.267 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Indexed 60 empty documents

In [6]:
print(os.path.exists("terrier_index.zip"))

True

In [7]:
#Si le chargement de la collection est trop long à cause du débit ou autres raisons,
# il est possible de récupérer directement l'index fourni par Terrier
import os

if not os.path.exists("terrier_index.zip"):
  !wget http://www.dcs.gla.ac.uk/~craigm/ecir2021-tutorial/terrier_index.zip
  !unzip -j terrier_index.zip -d terrier_index

index_ref = pt.IndexRef.of("./terrier_index/data.properties")
index = pt.IndexFactory.of(index_ref)

## Modèles de ré-ordonancement neuronaux "from scratch"

Les modèles de ré-ordonnancement dans OpenNIR sont constitués de deux éléments :
*  ranker: un modèle d'ordonnancement (e.g., drmm, knrm, pacrr, ...). Cf la liste des [Rankers](https://opennir.net/rankers.html). Il est également possible de rajouter des modèles d'ordonnancement en étendant la classe Ranker.
*  vocab : défnit comment le texte est encodé par le modèle (e.g., wordvec_hash, bert, ...). Cela permet ainsi de tester plusieurs méthodes de représentation. Plus de détails concernant le [vocab](https://opennir.net/vocab.html).

Les modèles de réordonnancement s'appuient sur une première étape d'ordonnancement (souvent BM25), récupèrent ensuite les textes des top documents et appliquent ensuite le modèle neuronal.

In [8]:
knrm = onir_pt.reranker('knrm', 'wordvec_hash', text_field='abstract')

config file not found: config
[2026-04-13 10:23:19,977][WordvecHashVocab][DEBUG] [starting] downloading https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip

[2026-04-13 10:23:33,487][onir.util.download][WARNING] no hash provided for https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip; consider adding expected_md5="3cc8839ac3fa9a6187149b1e73328b2a" to ensure data integrity.
[2026-04-13 10:23:33,491][onir.util.download][DEBUG] downloaded https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip [13.22s] [682M] [54.5MB/s]
[2026-04-13 10:23:33,496][WordvecHashVocab][DEBUG] [finished] downloading https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip [13.52s]
[2026-04-13 10:23:33,497][WordvecHashVocab][DEBUG] [starting] extracting vecs
[2026-04-13 10:23:55,443][WordvecHashVocab][DEBUG] [finished] extracting vecs [21.95s]
[2026-04-13 10:23:55,444][WordvecHashVocab][DEBUG] [starting] loading vecs into memory
[2026-04-13 10:26:09,589][WordvecHashVocab][DEBUG] [finished] loading vecs into memory [02:14]
[2026-04-13 10:26:09,850][WordvecHashVocab][DEBUG] [starting] writing cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p
[2026-04-13 10:26:45,255][WordvecHashVocab][DEBUG] [finished] writing cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p [35.41s]

Une fois le modèle chargé, il est nécessaire de mettre en place la pipeline d'évaluation vue dans le tp1.
Le modèle neuronal n'est pas efficace car il n'a pas été entraîné et utilise des poids aléatoires.

In [9]:
br = pt.BatchRetrieve(index) % 100
pipeline = br >> pt.text.get_text(dataset, 'abstract') >> knrm
pt.Experiment(
    [br, pipeline],
    topics,
    qrels,
    names=['DPH', 'DPH >> KNRM'],
    eval_metrics=["map", "ndcg", 'ndcg_cut.10', 'P.10', 'mrt']
)

/tmp/ipykernel_380/3806215551.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  br = pt.BatchRetrieve(index) % 100

[2026-04-13 10:28:47,997][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:28:48,597][onir_pt][DEBUG] [starting] batches

batches: 0it [6ms, ?it/s]

[2026-04-13 10:28:48,610][onir_pt][DEBUG] [finished] batches: [12ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: DPH >> KNRM ((TerrierRetr(DPH) >> RankCutoff(100) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22d10fd010> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-04-13 10:28:56,364][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:28:56,365][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/1250 [6ms<?, ?it/s]

[2026-04-13 10:28:59,638][onir_pt][DEBUG] [finished] batches: [3.27s] [1250it] [381.88it/s]

          name       map   P.10      ndcg  ndcg_cut.10          mrt
0          DPH  0.068056  0.658  0.165653     0.609058  3628.122552
1  DPH >> KNRM  0.054808  0.450  0.145487     0.359965  7262.222804

## Entraînement des modèles sur les jeux de données

Pour entraîner les modèles, il est nécessaire de construire la pipeline de modèles/transformations à utliser et ensuite d'appliquer la fonction .fit() à la pipeline.
Le code ci-dessous prend beaucoup de temps. Il est donné à titre indicatif si vous souhaitez l'utiliser sur des serveurs adaptés. L'étape suivante permet de charger directement les poids du modèle pré-entraîné à l'avance et mis à disposition de la communauté.

Dans ce qui suit, on utilise le jeu de données MS MARCO medical pour pré-entraîner le modèle qui sera ensuite appliqué sur CORD19.
Il est également possible de garder seulement le jeu de données CORD19, de le découper en train/val/test et regarder les performances.

In [17]:
# Apprentissage du modèle sur des données médicales (MS MARCO medical)
from sklearn.model_selection import train_test_split
train_ds = pt.datasets.get_dataset('irds:msmarco-passage/train/medical')
train_topics, valid_topics = train_test_split(train_ds.get_topics(), test_size=50, random_state=42)

# Indexation de MS MARCO pour la première étape d'ordonnancement et récupérer les textes (pour le ranker openNIR)
indexer = pt.index.IterDictIndexer(
    './terrier_msmarco-passage',
    text_attrs=['text'],
    meta={'docno': 20} # Specify 'docno' and its maximum byte length here
)
tr_index_ref = indexer.index(train_ds.get_corpus_iter())

pipeline = (pt.BatchRetrieve(tr_index_ref) % 100 # récupère les 100 premiers documents
            >> pt.text.get_text(train_ds, 'text') # récupère le texte de ces documents
            >> pt.apply.generic(lambda df: df.rename(columns={'text': 'abstract'})) # renomme la colonne
            >> knrm) # applique le re-ranker


pipeline.fit(
    train_topics,
    train_ds.get_qrels(),
    valid_topics,
    train_ds.get_qrels())

msmarco-passage/train/medical documents:   0%|          | 0/8841823 [6ms<?, ?it/s]

[INFO] If you have a local copy of https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/31644046b18952c1386cd4564ba2ae69
[INFO] [starting] https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz

https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 0.0%| 0.00/1.06G [0ms<?, ?B/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 0.0%| 459k/1.06G [118ms<04:31, 3.90MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 0.2%| 2.21M/1.06G [220ms<01:45, 10.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 0.7%| 7.12M/1.06G [322ms<47.53s, 22.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 1.7%| 18.2M/1.06G [438ms<25.00s, 41.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 2.8%| 29.3M/1.06G [657ms<23.03s, 44.7MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 3.8%| 40.4M/1.06G [1.04s<26.06s, 39.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 4.9%| 51.6M/1.06G [1.39s<27.15s, 37.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 5.9%| 62.7M/1.06G [1.75s<27.78s, 35.8MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 7.0%| 73.8M/1.06G [2.10s<28.04s, 35.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 8.0%| 84.9M/1.06G [2.45s<28.02s, 34.7MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 9.1%| 96.0M/1.06G [2.78s<27.90s, 34.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 10.1%| 107M/1.06G [3.12s<27.73s, 34.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 11.2%| 118M/1.06G [3.44s<27.35s, 34.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 12.2%| 129M/1.06G [3.77s<27.07s, 34.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 13.3%| 140M/1.06G [4.08s<26.65s, 34.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 14.3%| 152M/1.06G [4.40s<26.33s, 34.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 15.4%| 163M/1.06G [4.71s<25.93s, 34.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 16.4%| 174M/1.06G [5.02s<25.53s, 34.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 17.5%| 185M/1.06G [6.11s<28.86s, 30.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 18.5%| 196M/1.06G [6.35s<27.92s, 30.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 19.6%| 207M/1.06G [6.78s<27.87s, 30.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 20.6%| 218M/1.06G [7.20s<27.69s, 30.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 21.7%| 229M/1.06G [7.61s<27.51s, 30.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 22.7%| 240M/1.06G [8.00s<27.21s, 30.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 23.8%| 252M/1.06G [8.39s<26.89s, 30.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 24.8%| 263M/1.06G [8.76s<26.53s, 30.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 25.9%| 274M/1.06G [9.15s<26.21s, 29.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 26.9%| 285M/1.06G [9.52s<25.83s, 29.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 28.0%| 296M/1.06G [9.89s<25.45s, 29.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 29.0%| 307M/1.06G [10.25s<25.05s, 30.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 30.1%| 318M/1.06G [10.61s<24.67s, 30.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 31.1%| 329M/1.06G [10.97s<24.26s, 30.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 32.2%| 340M/1.06G [11.33s<23.88s, 30.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 33.2%| 351M/1.06G [11.68s<23.47s, 30.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 34.3%| 363M/1.06G [12.01s<23.03s, 30.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 35.3%| 374M/1.06G [12.34s<22.60s, 30.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 36.4%| 385M/1.06G [12.67s<22.16s, 30.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 37.4%| 396M/1.06G [13.00s<21.72s, 30.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 38.5%| 407M/1.06G [13.31s<21.29s, 30.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 39.5%| 418M/1.06G [13.63s<20.85s, 30.7MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 40.6%| 429M/1.06G [13.94s<20.41s, 30.8MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 41.6%| 440M/1.06G [14.25s<19.98s, 30.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 42.7%| 451M/1.06G [14.54s<19.52s, 31.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 43.7%| 463M/1.06G [14.84s<19.10s, 31.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 44.8%| 474M/1.06G [15.13s<18.65s, 31.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 45.8%| 485M/1.06G [15.41s<18.22s, 31.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 46.9%| 496M/1.06G [15.70s<17.79s, 31.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 47.9%| 507M/1.06G [15.98s<17.36s, 31.7MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 49.0%| 518M/1.06G [16.25s<16.93s, 31.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 50.0%| 529M/1.06G [16.53s<16.51s, 32.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 51.1%| 540M/1.06G [16.80s<16.09s, 32.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 52.1%| 551M/1.06G [17.07s<15.67s, 32.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 53.2%| 563M/1.06G [17.33s<15.26s, 32.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 54.2%| 574M/1.06G [17.59s<14.85s, 32.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 55.3%| 585M/1.06G [17.86s<14.44s, 32.8MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 56.3%| 596M/1.06G [18.12s<14.04s, 32.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 57.4%| 607M/1.06G [18.37s<13.64s, 33.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 58.4%| 618M/1.06G [18.62s<13.25s, 33.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 59.5%| 629M/1.06G [18.88s<12.86s, 33.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 60.5%| 640M/1.06G [19.12s<12.46s, 33.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 61.6%| 651M/1.06G [19.36s<12.08s, 33.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 62.6%| 663M/1.06G [19.60s<11.69s, 33.8MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 63.7%| 674M/1.06G [19.84s<11.31s, 34.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 64.7%| 685M/1.06G [20.08s<10.94s, 34.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 65.8%| 696M/1.06G [20.31s<10.56s, 34.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 66.8%| 707M/1.06G [20.54s<10.19s, 34.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 67.9%| 718M/1.06G [20.78s<9.83s, 34.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 68.9%| 729M/1.06G [21.00s<9.46s, 34.7MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 70.0%| 740M/1.06G [21.23s<9.11s, 34.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 71.0%| 751M/1.06G [21.46s<8.75s, 35.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 72.1%| 762M/1.06G [21.68s<8.40s, 35.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 73.1%| 774M/1.06G [21.90s<8.04s, 35.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 74.2%| 785M/1.06G [22.13s<7.70s, 35.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 75.2%| 796M/1.06G [22.33s<7.35s, 35.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 76.3%| 807M/1.06G [22.54s<7.00s, 35.8MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 77.3%| 818M/1.06G [22.74s<6.66s, 36.0MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 78.4%| 829M/1.06G [22.93s<6.32s, 36.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 79.4%| 840M/1.06G [23.14s<5.99s, 36.3MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 80.5%| 851M/1.06G [23.53s<5.70s, 36.2MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 81.5%| 862M/1.06G [23.91s<5.41s, 36.1MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 82.6%| 874M/1.06G [24.30s<5.12s, 35.9MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 83.6%| 885M/1.06G [24.69s<4.83s, 35.8MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 84.7%| 896M/1.06G [25.06s<4.53s, 35.7MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 85.7%| 907M/1.06G [25.42s<4.23s, 35.7MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 86.8%| 918M/1.06G [25.76s<3.92s, 35.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 87.8%| 929M/1.06G [26.11s<3.61s, 35.6MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 88.9%| 940M/1.06G [26.45s<3.31s, 35.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 89.9%| 951M/1.06G [26.78s<3.00s, 35.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 91.0%| 962M/1.06G [27.11s<2.68s, 35.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 92.0%| 974M/1.06G [27.44s<2.37s, 35.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 93.1%| 985M/1.06G [27.76s<2.06s, 35.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 94.1%| 996M/1.06G [28.09s<1.75s, 35.5MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 95.2%| 1.01G/1.06G [28.41s<1.43s, 35.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 96.2%| 1.02G/1.06G [28.74s<1.12s, 35.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 97.3%| 1.03G/1.06G [29.06s<809ms, 35.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 98.3%| 1.04G/1.06G [29.38s<495ms, 35.4MB/s]
https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: 99.4%| 1.05G/1.06G [29.70s<181ms, 35.4MB/s]
[INFO] [finished] https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: [29.87s] [1.06GB] [35.4MB/s]

https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz: [29.88s] [1.06GB] [35.4MB/s]
                                                                                                                 [INFO] [starting] fixing encoding

fixing encoding: 0.00B [0ms, ?B/s]
fixing encoding: 235kB [101ms, 2.33MB/s]
fixing encoding: 488kB [201ms, 2.43MB/s]
fixing encoding: 760kB [301ms, 2.52MB/s]
fixing encoding: 1.04MB [401ms, 2.59MB/s]
fixing encoding: 1.32MB [524ms, 2.52MB/s]
fixing encoding: 1.60MB [640ms, 2.50MB/s]
fixing encoding: 1.88MB [744ms, 2.53MB/s]
fixing encoding: 2.16MB [849ms, 2.55MB/s]
fixing encoding: 2.45MB [972ms, 2.52MB/s]
fixing encoding: 2.73MB [1.08s, 2.52MB/s]
fixing encoding: 3.13MB [1.18s, 2.64MB/s]
fixing encoding: 3.53MB [1.28s, 2.75MB/s]
fixing encoding: 4.01MB [1.38s, 2.89MB/s]
fixing encoding: 4.50MB [1.48s, 3.03MB/s]
fixing encoding: 5.00MB [1.59s, 3.15MB/s]
fixing encoding: 5.50MB [1.69s, 3.26MB/s]
fixing encoding: 6.00MB [1.79s, 3.35MB/s]
fixing encoding: 6.50MB [1.90s, 3.42MB/s]
fixing encoding: 7.00MB [2.00s, 3.50MB/s]
fixing encoding: 7.51MB [2.10s, 3.57MB/s]
fixing encoding: 8.02MB [2.20s, 3.64MB/s]
fixing encoding: 8.53MB [2.32s, 3.67MB/s]
fixing encoding: 9.03MB [2.43s, 3.72MB/s]
fixing encoding: 9.54MB [2.53s, 3.77MB/s]
fixing encoding: 10.0MB [2.63s, 3.82MB/s]
fixing encoding: 10.6MB [2.73s, 3.87MB/s]
fixing encoding: 11.1MB [2.85s, 3.88MB/s]
fixing encoding: 11.6MB [2.95s, 3.92MB/s]
fixing encoding: 12.1MB [3.05s, 3.96MB/s]
fixing encoding: 12.6MB [3.15s, 4.00MB/s]
fixing encoding: 13.1MB [3.26s, 4.03MB/s]
fixing encoding: 13.6MB [3.38s, 4.04MB/s]
fixing encoding: 14.2MB [3.49s, 4.05MB/s]
fixing encoding: 14.7MB [3.60s, 4.07MB/s]
fixing encoding: 15.2MB [3.71s, 4.09MB/s]
fixing encoding: 15.7MB [3.82s, 4.11MB/s]
fixing encoding: 16.2MB [3.93s, 4.13MB/s]
fixing encoding: 16.7MB [4.03s, 4.15MB/s]
fixing encoding: 17.3MB [4.14s, 4.17MB/s]
fixing encoding: 17.8MB [4.24s, 4.19MB/s]
fixing encoding: 18.3MB [4.35s, 4.20MB/s]
fixing encoding: 18.8MB [4.46s, 4.21MB/s]
fixing encoding: 19.3MB [4.57s, 4.23MB/s]
fixing encoding: 19.8MB [4.69s, 4.23MB/s]
fixing encoding: 20.4MB [4.80s, 4.24MB/s]
fixing encoding: 20.9MB [4.91s, 4.26MB/s]
fixing encoding: 21.4MB [5.01s, 4.28MB/s]
fixing encoding: 21.9MB [5.11s, 4.29MB/s]
fixing encoding: 22.4MB [5.21s, 4.31MB/s]
fixing encoding: 23.0MB [5.33s, 4.31MB/s]
fixing encoding: 23.5MB [5.46s, 4.30MB/s]
fixing encoding: 24.0MB [5.57s, 4.31MB/s]
fixing encoding: 24.5MB [5.68s, 4.32MB/s]
fixing encoding: 25.1MB [5.79s, 4.33MB/s]
fixing encoding: 25.6MB [5.90s, 4.33MB/s]
fixing encoding: 26.1MB [6.02s, 4.33MB/s]
fixing encoding: 26.6MB [6.14s, 4.33MB/s]
fixing encoding: 27.1MB [6.25s, 4.34MB/s]
fixing encoding: 27.7MB [6.36s, 4.35MB/s]
fixing encoding: 28.2MB [6.48s, 4.35MB/s]
fixing encoding: 28.7MB [6.58s, 4.36MB/s]
fixing encoding: 29.2MB [6.69s, 4.37MB/s]
fixing encoding: 29.7MB [6.80s, 4.38MB/s]
fixing encoding: 30.3MB [6.90s, 4.38MB/s]
fixing encoding: 30.8MB [7.01s, 4.39MB/s]
fixing encoding: 31.3MB [7.11s, 4.40MB/s]
fixing encoding: 31.8MB [7.21s, 4.41MB/s]
fixing encoding: 32.4MB [7.33s, 4.42MB/s]
fixing encoding: 32.9MB [7.44s, 4.42MB/s]
fixing encoding: 33.4MB [7.56s, 4.42MB/s]
fixing encoding: 33.9MB [7.66s, 4.43MB/s]
fixing encoding: 34.5MB [7.77s, 4.44MB/s]
fixing encoding: 35.0MB [7.87s, 4.44MB/s]
fixing encoding: 35.5MB [7.99s, 4.44MB/s]
fixing encoding: 36.0MB [8.10s, 4.45MB/s]
fixing encoding: 36.6MB [8.20s, 4.46MB/s]
fixing encoding: 37.1MB [8.31s, 4.46MB/s]
fixing encoding: 37.6MB [8.41s, 4.47MB/s]
fixing encoding: 38.1MB [8.53s, 4.47MB/s]
fixing encoding: 38.7MB [8.64s, 4.48MB/s]
fixing encoding: 39.2MB [8.74s, 4.48MB/s]
fixing encoding: 39.7MB [8.85s, 4.49MB/s]
fixing encoding: 40.2MB [8.95s, 4.49MB/s]
fixing encoding: 40.8MB [9.07s, 4.50MB/s]
fixing encoding: 41.3MB [9.18s, 4.50MB/s]
fixing encoding: 41.8MB [9.30s, 4.50MB/s]
fixing encoding: 42.3MB [9.41s, 4.50MB/s]
fixing encoding: 42.9MB [9.52s, 4.51MB/s]
fixing encoding: 43.4MB [9.64s, 4.50MB/s]
fixing encoding: 43.9MB [9.75s, 4.50MB/s]
fixing encoding: 44.5MB [9.87s, 4.51MB/s]
fixing encoding: 45.0MB [9.98s, 4.51MB/s]
fixing encoding: 45.5MB [10.11s, 4.50MB/s]
fixing encoding: 46.0MB [10.22s, 4.51MB/s]
fixing encoding: 46.6MB [10.33s, 4.51MB/s]
fixing encoding: 47.1MB [10.45s, 4.51MB/s]
fixing encoding: 47.6MB [10.55s, 4.51MB/s]
fixing encoding: 48.2MB [10.67s, 4.51MB/s]
fixing encoding: 48.7MB [10.78s, 4.52MB/s]
fixing encoding: 49.2MB [10.89s, 4.52MB/s]
fixing encoding: 49.8MB [10.99s, 4.53MB/s]
fixing encoding: 50.3MB [11.10s, 4.53MB/s]
fixing encoding: 50.8MB [11.30s, 4.50MB/s]
fixing encoding: 51.3MB [11.49s, 4.47MB/s]
fixing encoding: 51.9MB [11.69s, 4.44MB/s]
fixing encoding: 52.4MB [11.90s, 4.40MB/s]
fixing encoding: 52.9MB [12.10s, 4.37MB/s]
fixing encoding: 53.5MB [12.31s, 4.34MB/s]
fixing encoding: 54.0MB [12.54s, 4.31MB/s]
fixing encoding: 54.5MB [12.78s, 4.27MB/s]
fixing encoding: 55.1MB [12.99s, 4.24MB/s]
fixing encoding: 55.6MB [13.19s, 4.22MB/s]
fixing encoding: 56.1MB [13.39s, 4.19MB/s]
fixing encoding: 56.7MB [13.60s, 4.17MB/s]
fixing encoding: 57.2MB [13.81s, 4.14MB/s]
fixing encoding: 57.7MB [13.98s, 4.13MB/s]
fixing encoding: 58.3MB [14.09s, 4.13MB/s]
fixing encoding: 58.8MB [14.20s, 4.14MB/s]
fixing encoding: 59.3MB [14.31s, 4.15MB/s]
fixing encoding: 59.9MB [14.43s, 4.15MB/s]
fixing encoding: 60.4MB [14.54s, 4.15MB/s]
fixing encoding: 60.9MB [14.65s, 4.16MB/s]
fixing encoding: 61.5MB [14.77s, 4.16MB/s]
fixing encoding: 62.0MB [14.90s, 4.16MB/s]
fixing encoding: 62.5MB [15.02s, 4.16MB/s]
fixing encoding: 63.1MB [15.14s, 4.17MB/s]
fixing encoding: 63.6MB [15.27s, 4.17MB/s]
fixing encoding: 64.1MB [15.38s, 4.17MB/s]
fixing encoding: 64.7MB [15.51s, 4.17MB/s]
fixing encoding: 65.2MB [15.63s, 4.17MB/s]
fixing encoding: 65.8MB [15.75s, 4.18MB/s]
fixing encoding: 66.3MB [15.89s, 4.17MB/s]
fixing encoding: 66.8MB [16.01s, 4.17MB/s]
fixing encoding: 67.4MB [16.13s, 4.18MB/s]
fixing encoding: 67.9MB [16.26s, 4.18MB/s]
fixing encoding: 68.4MB [16.40s, 4.17MB/s]
fixing encoding: 69.0MB [16.51s, 4.18MB/s]
fixing encoding: 69.5MB [16.68s, 4.17MB/s]
fixing encoding: 70.0MB [17.06s, 4.11MB/s]
fixing encoding: 70.6MB [17.16s, 4.11MB/s]
fixing encoding: 71.1MB [17.28s, 4.12MB/s]
fixing encoding: 71.7MB [17.39s, 4.12MB/s]
fixing encoding: 72.2MB [17.51s, 4.12MB/s]
fixing encoding: 72.7MB [17.87s, 4.07MB/s]
fixing encoding: 73.3MB [18.05s, 4.06MB/s]
fixing encoding: 73.8MB [18.15s, 4.07MB/s]
fixing encoding: 74.4MB [18.26s, 4.07MB/s]
fixing encoding: 74.9MB [18.37s, 4.08MB/s]
fixing encoding: 75.4MB [18.48s, 4.08MB/s]
fixing encoding: 76.0MB [18.69s, 4.06MB/s]
fixing encoding: 76.5MB [19.00s, 4.03MB/s]
fixing encoding: 77.1MB [19.11s, 4.03MB/s]
fixing encoding: 77.6MB [19.21s, 4.04MB/s]
fixing encoding: 78.1MB [19.32s, 4.04MB/s]
fixing encoding: 78.7MB [19.44s, 4.05MB/s]
fixing encoding: 79.2MB [19.55s, 4.05MB/s]
fixing encoding: 79.8MB [19.67s, 4.06MB/s]

KeyboardInterrupt:

Pour éviter l'étape d'entraînement ici, on utlise une version pré-entraînée.

**Important** : penser à supprimer la mémoire des re-rankers qui vont être mis à jour avec les modèles pré-entrainés.

In [18]:
del knrm # free up the memory before loading a new version of the ranker
knrm = onir_pt.reranker.from_checkpoint('https://macavaney.us/knrm.medmarco.tar.gz', text_field='abstract', expected_md5="d70b1d4f899690dae51161537e69ed5a")

[2026-04-13 10:40:23,161][onir.util.download][DEBUG] downloaded https://macavaney.us/knrm.medmarco.tar.gz [0ms] [1.43k] [7.51MB/s] [md5 hash verified]
[2026-04-13 10:40:23,170][WordvecHashVocab][DEBUG] [starting] reading cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p
[2026-04-13 10:40:32,444][WordvecHashVocab][DEBUG] [finished] reading cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p [9.27s]

Il est ensuire possible de lancer la pipeline d'évaluation avec ce nouveau modèle. Les résultats sont meilleurs !

In [19]:
pipeline = br >> pt.text.get_text(dataset, 'abstract') >> knrm
pt.Experiment(
    [br, pipeline],
    topics,
    qrels,
    names=['DPH', 'DPH >> KNRM'],
    baseline=0,       ## spécifie quelle est le modèle de référence pour calculer les améliorations.
    eval_metrics=["map", "ndcg", 'ndcg_cut.10', 'P.10', 'mrt']
)

[2026-04-13 10:40:38,449][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:40:38,760][onir_pt][DEBUG] [starting] batches

batches: 0it [6ms, ?it/s]

[2026-04-13 10:40:38,774][onir_pt][DEBUG] [finished] batches: [13ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: DPH >> KNRM ((TerrierRetr(DPH) >> RankCutoff(100) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22aa1644d0> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-04-13 10:40:44,567][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:40:44,567][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/1250 [15ms<?, ?it/s]

[2026-04-13 10:40:47,709][onir_pt][DEBUG] [finished] batches: [3.14s] [1250it] [397.95it/s]

,name,map,P.10,ndcg,ndcg_cut.10,mrt,map +,map -,map p-value,P.10 +,P.10 -,P.10 p-value,ndcg +,ndcg -,ndcg p-value,ndcg_cut.10 +,ndcg_cut.10 -,ndcg_cut.10 p-value
0,DPH,0.068056,0.658,0.165653,0.609058,2069.806677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DPH >> KNRM,0.065106,0.598,0.160562,0.532655,6726.705509,20.0,30.0,0.09626,12.0,26.0,0.024604,20.0,30.0,0.028326,20.0,30.0,0.005972

**Exercice 1**
Autre pipeline. A vous de deviner ce qu'elle fait !

In [20]:
cutoffs = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
dph = pt.BatchRetrieve(index)
res = pt.Experiment(
    [dph % cutoff >> pt.text.get_text(dataset, 'abstract') >> knrm for cutoff in cutoffs],
    dataset.get_topics('description'),
    dataset.get_qrels(),
    names=[f'c={cutoff}' for cutoff in cutoffs],
    eval_metrics=["map", "recip_rank", "ndcg", "ndcg_cut.10", "mrt"]
)
res

[2026-04-13 10:42:42,638][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,639][onir_pt][DEBUG] [starting] batches

/tmp/ipykernel_380/2093709227.py:2: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  dph = pt.BatchRetrieve(index)

batches: 0it [7ms, ?it/s]

[2026-04-13 10:42:42,653][onir_pt][DEBUG] [finished] batches: [14ms] [0it] [?it/s]
[2026-04-13 10:42:42,668][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,668][onir_pt][DEBUG] [starting] batches

batches: 0it [10ms, ?it/s]

[2026-04-13 10:42:42,689][onir_pt][DEBUG] [finished] batches: [21ms] [0it] [?it/s]
[2026-04-13 10:42:42,707][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,708][onir_pt][DEBUG] [starting] batches

batches: 0it [14ms, ?it/s]

[2026-04-13 10:42:42,727][onir_pt][DEBUG] [finished] batches: [19ms] [0it] [?it/s]
[2026-04-13 10:42:42,744][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,745][onir_pt][DEBUG] [starting] batches

batches: 0it [15ms, ?it/s]

[2026-04-13 10:42:42,766][onir_pt][DEBUG] [finished] batches: [21ms] [0it] [?it/s]
[2026-04-13 10:42:42,781][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,782][onir_pt][DEBUG] [starting] batches

batches: 0it [14ms, ?it/s]

[2026-04-13 10:42:42,802][onir_pt][DEBUG] [finished] batches: [19ms] [0it] [?it/s]
[2026-04-13 10:42:42,816][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,817][onir_pt][DEBUG] [starting] batches

batches: 0it [13ms, ?it/s]

[2026-04-13 10:42:42,835][onir_pt][DEBUG] [finished] batches: [18ms] [0it] [?it/s]
[2026-04-13 10:42:42,851][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,852][onir_pt][DEBUG] [starting] batches

batches: 0it [14ms, ?it/s]

[2026-04-13 10:42:42,871][onir_pt][DEBUG] [finished] batches: [19ms] [0it] [?it/s]
[2026-04-13 10:42:42,887][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,888][onir_pt][DEBUG] [starting] batches

batches: 0it [14ms, ?it/s]

[2026-04-13 10:42:42,908][onir_pt][DEBUG] [finished] batches: [20ms] [0it] [?it/s]
[2026-04-13 10:42:42,921][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,921][onir_pt][DEBUG] [starting] batches

batches: 0it [13ms, ?it/s]

[2026-04-13 10:42:42,939][onir_pt][DEBUG] [finished] batches: [17ms] [0it] [?it/s]
[2026-04-13 10:42:42,951][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:42,951][onir_pt][DEBUG] [starting] batches

batches: 0it [12ms, ?it/s]

[2026-04-13 10:42:42,969][onir_pt][DEBUG] [finished] batches: [17ms] [0it] [?it/s]

/usr/local/lib/python3.12/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #0: c=10 ((TerrierRetr(DPH) >> RankCutoff(10) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd123c0> >> onir(knrm,wordvec_hash)))
 - Pipeline #1: c=20 ((TerrierRetr(DPH) >> RankCutoff(20) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd11b20> >> onir(knrm,wordvec_hash)))
 - Pipeline #2: c=30 ((TerrierRetr(DPH) >> RankCutoff(30) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd12930> >> onir(knrm,wordvec_hash)))
 - Pipeline #3: c=40 ((TerrierRetr(DPH) >> RankCutoff(40) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd11700> >> onir(knrm,wordvec_hash)))
 - Pipeline #4: c=50 ((TerrierRetr(DPH) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd135f0> >> onir(knrm,wordvec_hash)))
 - Pipeline #5: c=60 ((TerrierRetr(DPH) >> RankCutoff(60) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd11280> >> onir(knrm,wordvec_hash)))
 - Pipeline #6: c=70 ((TerrierRetr(DPH) >> RankCutoff(70) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd13440> >> onir(knrm,wordvec_hash)))
 - Pipeline #7: c=80 ((TerrierRetr(DPH) >> RankCutoff(80) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd13830> >> onir(knrm,wordvec_hash)))
 - Pipeline #8: c=90 ((TerrierRetr(DPH) >> RankCutoff(90) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd13d40> >> onir(knrm,wordvec_hash)))
 - Pipeline #9: c=100 ((TerrierRetr(DPH) >> RankCutoff(100) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7b22cfd10080> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-04-13 10:42:45,247][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:45,248][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/125 [7ms<?, ?it/s]

[2026-04-13 10:42:45,562][onir_pt][DEBUG] [finished] batches: [314ms] [125it] [398.58it/s]
[2026-04-13 10:42:47,645][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:47,646][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/250 [7ms<?, ?it/s]

[2026-04-13 10:42:48,215][onir_pt][DEBUG] [finished] batches: [569ms] [250it] [439.75it/s]
[2026-04-13 10:42:50,317][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:50,317][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/375 [6ms<?, ?it/s]

[2026-04-13 10:42:51,361][onir_pt][DEBUG] [finished] batches: [1.04s] [375it] [359.65it/s]
[2026-04-13 10:42:54,522][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:54,523][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/500 [6ms<?, ?it/s]

[2026-04-13 10:42:55,698][onir_pt][DEBUG] [finished] batches: [1.17s] [500it] [425.75it/s]
[2026-04-13 10:42:57,864][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:42:57,865][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/625 [6ms<?, ?it/s]

[2026-04-13 10:42:59,217][onir_pt][DEBUG] [finished] batches: [1.35s] [625it] [462.30it/s]
[2026-04-13 10:43:01,434][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:43:01,435][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/750 [6ms<?, ?it/s]

[2026-04-13 10:43:03,204][onir_pt][DEBUG] [finished] batches: [1.77s] [750it] [423.96it/s]
[2026-04-13 10:43:06,448][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:43:06,449][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/875 [7ms<?, ?it/s]

[2026-04-13 10:43:08,395][onir_pt][DEBUG] [finished] batches: [1.95s] [875it] [449.57it/s]
[2026-04-13 10:43:10,466][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:43:10,466][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/1000 [6ms<?, ?it/s]

[2026-04-13 10:43:12,629][onir_pt][DEBUG] [finished] batches: [2.16s] [1000it] [462.58it/s]
[2026-04-13 10:43:14,700][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:43:14,701][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/1125 [6ms<?, ?it/s]

[2026-04-13 10:43:17,741][onir_pt][DEBUG] [finished] batches: [3.04s] [1125it] [370.15it/s]
[2026-04-13 10:43:20,143][onir_pt][DEBUG] using GPU (deterministic)
[2026-04-13 10:43:20,144][onir_pt][DEBUG] [starting] batches

batches:   0%|          | 0/1250 [6ms<?, ?it/s]

[2026-04-13 10:43:22,829][onir_pt][DEBUG] [finished] batches: [2.69s] [1250it] [465.54it/s]

    name       map  recip_rank      ndcg  ndcg_cut.10          mrt
0   c=10  0.011837    0.785333  0.049385     0.597078  2581.975493
1   c=20  0.020948    0.787500  0.071907     0.587754  2531.674197
2   c=30  0.029344    0.805667  0.089957     0.598327  3026.065337
3   c=40  0.034927    0.808524  0.103090     0.582940  4115.460821
4   c=50  0.040713    0.825667  0.114788     0.591895  3384.025165
5   c=60  0.046934    0.815667  0.126097     0.589682  3866.670535
6   c=70  0.051910    0.816333  0.136295     0.578130  5064.109338
7   c=80  0.056876    0.804667  0.145015     0.565053  4111.312224
8   c=90  0.061705    0.806333  0.154461     0.569579  4988.100416
9  c=100  0.065106    0.767889  0.160562     0.532655  4856.753739

## Modèle Vanilla BERT

**Exercice 2**

Sur le même principe que le modèle KNRM, analyser les performances du modèle vanilla BERT sans et avec pré-entraînement.
Pour la version du modèle pré-entraîné, on utilisera le checkpoint ['https://macavaney.us/scibert-medmarco.tar.gz']('https://macavaney.us/scibert-medmarco.tar.gz') avec le paramètre expected_md5="854966d0b61543ffffa44cea627ab63b".

Synthétisez toutes les mesures d'évaluation dans un même tableau (bm25, knrm et Vanilla Bert / avec/sans entraînement).

# Autres modèles - hors OpenNIR
PyTerrier a mis a disposition l'implémentation d'autres modèles neuronaux:
- ColBERT : https://github.com/terrierteam/pyterrier_colbert
- T5 : https://github.com/terrierteam/pyterrier_t5
- Doc2Query : https://github.com/terrierteam/pyterrier_doc2query
- DeepCT : https://github.com/terrierteam/pyterrier_deepct
- ANCE : https://github.com/terrierteam/pyterrier_ance

Un exemple de code de code est donnée ci-dessous avec Mono-T5 :

In [ ]:
from pyterrier_t5 import MonoT5ReRanker
monoT5 = MonoT5ReRanker(text_field='abstract')

br = pt.BatchRetrieve(index) % 30
pipeline = (br >> pt.text.get_text(dataset, 'abstract') >> monoT5)
pt.Experiment(
    [br, pipeline],
    dataset.get_topics('description'),
    dataset.get_qrels(),
    names=['DPH', 'DPH >> T5'],
    eval_metrics=["map", "recip_rank", "ndcg", "ndcg_cut.10", "mrt"]
)